#!/bin/bash
set -e

if [ -t 1 ] ; then
    TTY_ENV_ARGS="-e LINES=$(tput lines) -e COLUMNS=$(tput cols)"
else
    TTY_ENV_ARGS=""
fi

docker exec \
    $TTY_ENV_ARGS \
    --privileged \
    --detach-keys 'ctrl-o,ctrl-d' \
    -it docker-bane-dev-1 \
    bash -c "cat /root/.bashrc && $*"
