version: '3'

services:

  bane-mysql:
    image: 'mysql:8'
    platform: 'linux/x86_64'
    restart: 'unless-stopped'
    environment:
      MYSQL_USER: 'bane'
      MYSQL_PASSWORD: 'bane'
      MYSQL_ROOT_PASSWORD: 'bane'
    expose:
      - '3306'
    ports:
      - '33221:3306'

  bane-postgres:
    image: 'postgres:14'
    restart: 'unless-stopped'
    environment:
      POSTGRES_USER: 'bane'
      POSTGRES_PASSWORD: 'bane'
    expose:
      - '5432'
    ports:
      - '33222:5432'

  bane-dev:
    build:
      context: '../'
      dockerfile: 'docker/dev/Dockerfile'
    restart: 'unless-stopped'
    cap_add:
      - 'SYS_PTRACE'
    security_opt:
      - 'apparmor:unconfined'
    volumes:
      - '.:/bane'
    depends_on:
      - 'bane-mysql'
      - 'bane-postgres'
    links:
      - 'bane-mysql'
      - 'bane-postgres'
    expose:
      - '8000'
    ports:
      - '33220:8000'

