name: Ci

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:

env:
  IMAGE_NAME: 'bane-ci'

jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'

      - uses: 'styfle/cancel-workflow-action@0.4.1'
        with:
          access_token: '${{ github.token }}'

      - name: 'Cache'
        uses: 'actions/cache@v2'
        id: 'cache'
        with:
          path: '~/.cache'
          key:
            bane-ci-${{ github.ref }}-${{ hashFiles(
              '.dockertimestamp',
              'docker/ci/Dockerfile',
              'go.mod',
              'go.sum'
            ) }}
          restore-keys: |
            bane-ci-${{ github.ref }}-
            bane-ci-

      - name: 'Docker cache load'
        run: >
          tar -tvf ~/.cache/docker/ci.tar ||: ;
          docker load -i ~/.cache/docker/ci.tar ||: ;
          docker image history wrmsr/bane-ci ||: ;

      - name: 'Run tests'
        run: >
          BANE_CI_DOCKER_OPTS='-v ${{ github.workspace }}:/github/workspace'
          BANE_CI_OUTPUT_DIR=/github/workspace
          make ci

      - name: 'Docker cache save'
        if: "steps.cache.outputs.cache-hit != 'true'"
        run: >
          mkdir -p ~/.cache/docker/ &&
          docker image history wrmsr/bane-ci &&
          docker history wrmsr/bane-ci | tail -n+2 | awk '{print $1}' | egrep -v '<missing>' |
            xargs docker save -o ~/.cache/docker/ci.tar wrmsr/bane-ci
