name: Ci

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:

jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'

      - uses: 'styfle/cancel-workflow-action@0.4.1'
        with:
          access_token: '${{ github.token }}'

      - name: 'Cache'
        uses: 'actions/cache@v2'
        id: 'cache'
        with:
          path: '~/.cache'
          key:
            ci-${{ github.ref }}-${{ hashFiles(
              '.dockertimestamp',
              '.versions',
              'docker/ci/Dockerfile',
              'docker/docker-compose-ext.yml',
              'go.mod',
              'go.sum'
            ) }}
          restore-keys: |
            ci-${{ github.ref }}-
            ci-

      - name: 'Docker cache load'
        run: >
          tar -tvf ~/.cache/docker/ci.tar ||: ;
          docker load -i ~/.cache/docker/ci.tar ||: ;
          docker image history wrmsr/bane-ci ||: ;

      - name: 'Run tests'
        run: >
          BANE_CI_DOCKER_OPTS='-v ${{ github.workspace }}:/github/workspace'
          BANE_CI_OUTPUT_DIR=/github/workspace
          make ci

      - name: 'Docker cache save'
        if: "steps.cache.outputs.cache-hit != 'true'"
        run: >
          mkdir -p ~/.cache/docker/ &&
          docker image history wrmsr/bane-ci &&
          (
            for IMG in $(
              echo wrmsr/bane-ci ;
              egrep '^\s*image:' docker/docker-compose-ext.yml | cut -d"'" -f2
            ) ; do
              echo "$IMG" ;
              docker history "$IMG" | tail -n+2 | awk '{print $1}' | egrep -v '<missing>' ; done
          ) | tee /dev/tty | xargs docker save -o ~/.cache/docker/ci.tar
